baseURL: https://urinfo24.com/
languageCode: ko-kr
title: Urinfo24

# Hugo Modules
module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3

# 다국어 설정
defaultContentLanguage: ko
languages:
  ko:
    languageName: 한국어
    title: Urinfo24
    weight: 1
  en:
    languageName: English
    title: Urinfo24
    weight: 2
  ja:
    languageName: 日本語
    title: Urinfo24
    weight: 3
  de:
    languageName: Deutsch
    title: Urinfo24
    weight: 4
  fr:
    languageName: Français
    title: Urinfo24
    weight: 5
  es:
    languageName: Español
    title: Urinfo24
    weight: 6
  vi:
    languageName: Tiếng Việt
    title: Urinfo24
    weight: 7
  th:
    languageName: ไทย
    title: Urinfo24
    weight: 8
  hi:
    languageName: हिन्दी
    title: Urinfo24
    weight: 9
  id:
    languageName: Bahasa Indonesia
    title: Urinfo24
    weight: 10

# 기본 설정
pagination:
  pagerSize: 10
hasCJKLanguage: true
enableRobotsTXT: true
