main:
  - identifier: home
    name: Home
    url: /
    weight: 1
    params:
      icon: home

social:
  - identifier: mail
    name: Email
    url: mailto:contack@urinfo24.com
    params:
      icon: mail
