main:
  - identifier: home
    name: Home
    url: /
    weight: 1
    params:
      icon: home
    
  - identifier: archives
    name: Archives
    url: /archives/
    weight: 2
    params:
      icon: archives
    
  - identifier: search
    name: Search
    url: /search/
    weight: 3
    params:
      icon: search

social:
  - identifier: github
    name: GitHub
    url: https://github.com/urfreein
    params:
      icon: brand-github
